### ISSUE TITLE
which dolfin-adjoint version to use

### ISSUE THREAD

**Issue by MiroK** [MiroK/adjoint-optim-control#1]
@sebastkm which dolfin-adjoint version should be used in order to get the `main.py` running? With
`fenicsproject run quay.io/dolfinadjoint/dolfin-adjoint` I am getting an error

>     Jhat = ReducedFunctional(J, [Control(m) for m in ctrls])
>   File "/home/fenics/local/lib/python2.7/site-packages/dolfin_adjoint/reduced_functional.py", line 39, in __init__
>     self.__check_input_types(functional, self.controls, scale, cache)
>   File "/home/fenics/local/lib/python2.7/site-packages/dolfin_adjoint/reduced_functional.py", line 116, in __check_input_types
>     raise TypeError("functional should be a Functional")
> TypeError: functional should be a Functional 

Here `J` is actually a float

**Comment by sebastkm** [comment]
You are using the old dolfin-adjoint (libadjoint) docker image. The new dolfin-adjoint (pyadjoint) docker images are located at:
`quay.io/dolfinadjoint/pyadjoint`

**Comment by MiroK** [comment]
Thanks, that fixed it!
